version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuee-app
    volumes:
      - .:/app # Monte le dossier local dans le conteneur
      - /app/node_modules # Empêche le montage du dossier node_modules local
    ports:
      - "5173:5173" # Mappe le port 3000 du conteneur au port 3000 de l'hôte
    command: npm run dev # Lance le serveur de développement Vue.js
    restart: unless-stopped
