version: '3.8'

services:
  frontend:
    build:
      context: ./max
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - chat_api

  chat_api:
    build:
      context: ./chat_api
    ports:
      - "8000:8000"
    restart: always
    environment:
      - MISTRAL_KEY=P896w2DBvu1lvS5eeF8yn0Paz1TWMBKH
