
services:
  mongo:
    image: mongo:6
    container_name: maxai-mongo
    ports: [ "27017:27017" ]
    volumes:
      - ./docker-data/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=maxai

  backend:
    build: ./server-app 
    container_name: maxai-backend
    env_file: ./server-app/.env
    ports: [ "3000:3000" ]
    depends_on: [ mongo ]
    volumes:
      - ./server-app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://mongo:27017/maxai
  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - chat_api
      - backend
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
   
  chat_api:
    build:
      context: ./chat_api
    ports:
      - "8000:8000"
    restart: always
    environment:
      - MISTRAL_KEY=P896w2DBvu1lvS5eeF8yn0Paz1TWMBKH
    volumes:
      - ./chat_api:/app 